# Railway deployment manifest for Laravel (PHP-FPM + artisan serve)

services:
  web:
    build:
      dockerfile: Dockerfile
      context: .
    env:
      APP_ENV: production
      APP_DEBUG: false
      APP_URL: ${RAILWAY_STATIC_URL}
      DB_CONNECTION: mysql
      DB_HOST: ${DB_HOST}
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      CACHE_DRIVER: file
      SESSION_DRIVER: file
      QUEUE_CONNECTION: sync
    start:
      cmd: >
        bash -c "
          composer install --no-dev --optimize-autoloader &&
          php artisan key:generate --force &&
          php artisan migrate --force &&
          php artisan serve --host=0.0.0.0 --port=80
        "
    healthcheck:
      path: /
      interval: 10
      timeout: 5
      retries: 3

  node:
    build:
      image: node:22
      context: .
    start:
      cmd: >
        bash -c "npm install && npm run build"
